[
  { tipo: "setCharacterCodeTable", payload: 19 },
  { tipo: "setCharacterCodeTable", payload: 19 },
  { tipo: "encode", payload: "cp858" },
  { tipo: "font", payload: "A" },
  { tipo: "text", payload: cabecera },
  {
    tipo: "text",
    payload: `Data: ${diasSemana[fechaEspaña.format("d")]} ${fechaEspaña.format(
      "DD-MM-YYYY HH:mm"
    )}`,
  },
  { tipo: "text", payload: "Factura simplificada N: " + numFactura },
  { tipo: "text", payload: "Ates per: " + nombreDependienta },
  { tipo: "text", payload: detalleClienteVip },
  { tipo: "text", payload: detalleNombreCliente },
  { tipo: "text", payload: detallePuntosCliente },
  { tipo: "text", payload: "" },
  { tipo: "text", payload: "" },
  { tipo: "text", payload: "" },
  {
    tipo: "text",
    payload: `Quantitat      Article   ${
      preuU ? "  Preu U." : ""
    }     Import (€)`,
  },
  { tipo: "text", payload: "-----------------------------------------" },
  { tipo: "align", payload: "LT" },
  { tipo: "text", payload: detalles },
  { tipo: "align", payload: "CT" },
  { tipo: "text", payload: pagoTarjeta },
  { tipo: "text", payload: pagoTkrs },
  { tipo: "align", payload: "LT" },
  { tipo: "text", payload: infoConsumoPersonal },
  { tipo: "align", payload: "CT" },
  { tipo: "text", payload: "----------------------------------------------" },
  { tipo: "align", payload: "LT" },
  { tipo: "size", payload: [1, 1] },
  { tipo: "text", payload: pagoDevolucion },
  { tipo: "text", payload: detalleEncargo },
  { tipo: "text", payload: detalleDejaCuenta },
  { tipo: "text", payload: "TOTAL: " + total.toFixed(2) + " €" },
  { tipo: "text", payload: "" },
  { tipo: "size", payload: [0, 0] },
  { tipo: "align", payload: "CT" },
  { tipo: "text", payload: "Base IVA         IVA         IMPORT" },
  { tipo: "text", payload: detalleIva },
  { tipo: "text", payload: copiaText },
  { tipo: "text", payload: firmaText },
  { tipo: "text", payload: "" },
  { tipo: "text", payload: "ID: " + random() + " - " + random() },
  { tipo: "text", payload: pie },
  { tipo: "text", payload: "" },
  { tipo: "text", payload: "" },
  { tipo: "text", payload: "" },
  { tipo: "cut", payload: "PAPER_FULL_CUT" },
];
