version: '3.8'
services:
  tocgame:
    container_name: tocBackend
    build: ./
    environment:
      MONGO_URL: "mongodb://mongodb:27017"
    depends_on:
      - mongodb
    ports:
     - 3000:3000
     - 5051:5051
    restart: unless-stopped
  mongodb:
    container_name: mongodb
    image: mongo:4.4
    volumes:
     - ~/mongo/data:/data/db
    ports:
     - 27017:27017
    restart: always
